apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bookinfo-vs
  namespace: default
spec:
  host: bookinfo.example.com
  upstreams:
  - name: productpage
    service: productpage
    port: 9080
  routes:  
  - path: /
    action:
      proxy: 
          upstream: productpage